name: Android CI

on:
    pull_request:
        branches: [ "compose", "jetpack" ]

    workflow_dispatch:

jobs:
    ktlint:
        permissions: write-all
        name: Check Code Quality(ktlint)
        runs-on: ubuntu-latest

        steps:
            -   name: Clone repo
                uses: actions/checkout@master
                with:
                    fetch-depth: 1
            -   name: ktlint
                uses: ScaCap/action-ktlint@master
                with:
                    github_token: ${{ secrets.github_token }}
                    reporter: github-pr-review # Change reporter

    detekt:
        name: Check Code Quality(detekt)
        runs-on: ubuntu-latest

        steps:
            -   name: Clone repo
                uses: actions/checkout@v4
                with:
                    fetch-depth: 1
                    ref: ${{ github.head_ref }}

            -   name: detekt
                uses: alaegin/Detekt-Action@v1.23.6
                with:
                    github_token: ${{ secrets.github_token }}
                    detekt_config: config/detekt-config.yml # Change config path

    build:
        name: check Build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Setup Android SDK
                uses: android-actions/setup-android@v3

            -   name: Gradle Caching
                uses: actions/cache@v4
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            - name: Grant execute permission for gradlew
              run: |
                echo sdk.dir=${{ env.ANDROID_HOME }} >> local.properties
                echo '${{ secrets.LOCAL_PROPERTIES }}' >> local.properties
                chmod +x gradlew

            -   name: add google_service.json
                run: |
                    echo '${{ secrets.GOOGLE_SERVICE_KEY }}' >> ${{ github.workspace }}/app/google-services.json

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Build with Gradle
                run: ./gradlew app:build --parallel -x lint -x test
