name: Android CD

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
        branches:
            - "develop"

    workflow_dispatch:

jobs:
    sign-apk:
        name: Sign app APK
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: add google_service.json
                run: |
                    echo '${{ secrets.GOOGLE_SERVICE_KEY }}' >> ${{ github.workspace }}/app/google-services.json
            -   name: build release
                run: |
                    echo sdk.dir=${{ env.ANDROID_HOME }} >> local.properties
                    echo '${{ secrets.LOCAL_PROPERTIES }}' >> local.properties
                    chmod +x gradlew
                    ./gradlew assembleProdRelease

            -   uses: r0adkll/sign-android-release@v1
                name: Sign app APK
                # ID used to access action output
                id: sign_app
                with:
                    releaseDirectory: app/build/outputs/apk/prod/release
                    signingKeyBase64: ${{ secrets.SIGNING_KEY }}
                    alias: ${{ secrets.ALIAS }}
                    keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
                    keyPassword: ${{ secrets.KEY_PASSWORD }}
                env:
                    # override default build-tools version (33.0.0) -- optional
                    BUILD_TOOLS_VERSION: "34.0.0"

            # Example use of `signedReleaseFile` output -- not needed
            -   uses: actions/upload-artifact@v4
                with:
                    name: Signed app bundle
                    path: ${{steps.sign_app.outputs.signedReleaseFile}}

            -   name: upload artifact to Firebase App Distribution
                uses: wzieba/Firebase-Distribution-Github-Action@v1
                with:
                    appId: ${{secrets.FIREBASE_APP_ID}}
                    serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
                    groups: testers
                    file: ${{ steps.sign_app.outputs.signedReleaseFile }}
                    releaseNotesFile: ${{ github.workspace }}/.github/releaseNote.txt

    get-version:
        needs: [ sign-apk ]
        name: create release
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            -   uses: actions/checkout@v4
            -   name: set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle
            -   name: Get Version
                run: |
                    versionName=$(grep "versionName" ${{github.workspace}}/app/build.gradle.kts | awk -F'=' '{ print $2 }' | tr -d ' "')
                    echo "version_name=$versionName" >> $GITHUB_ENV
            -   name: check version
                run: |
                    echo "${{ env.version_name }}"
            -   name: add version in body
                run: |
                    perl -p -i -e '$.==2 and print "###${{ env.version_name }}\n"' ${{ github.workspace}}/.github/body.md
            -   uses: actions/checkout@v4
            -   uses: ncipollo/release-action@v1
                with:
                    bodyFile: "${{ github.workspace}}/.github/body.md"
                    tag: "v${{ env.version_name }}"

    slack:
        needs: [ sign-apk ]
        name: Slack message
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            -   uses: actions/checkout@v4
            -   name: save Version
                run: |
                    versionName=$(grep "versionName" ./app/build.gradle.kts | awk -F'=' '{ print $2 }' | tr -d ' "')
                    echo "version_name=$versionName" >> $GITHUB_ENV
            -   name: check version
                run: |
                    echo "${{ env.version_name }}"
            -   name: save body message
                run: |
                    sed -n '/#### 기능 수정/,$p' ${{ github.workspace}}/.github/body.md > ${{ github.workspace}}/.github/body.txt
                    sed -e '/^#### /,$s/^#### //' ${{ github.workspace}}/.github/body.txt > ${{ github.workspace}}/.github/body2.txt
                    body=$(awk '{printf "%s\\n> ", $0}' ${{ github.workspace}}/.github/body2.txt)
                    echo "bodymessage=$body"
                    echo "body=$body" >> $GITHUB_ENV
            -   name: send message
                run: |
                    curl -H "Content-type: application/json" \
                    --data '{"channel":"${{ secrets.SLACK_CHANNEL_ID }}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"[AOS]\n*안드로이드 파이어베이스 `v${{ env.version_name }}`버전 배포 완료*\n 배포 내용\n> ${{ env.body }}"}}]}' \
                    -H "Authorization: Bearer ${{ secrets.SLACK_AUTHORIZATION }}" \
                    -X POST https://slack.com/api/chat.postMessage
