name: Android CD

on:
    pull_request:
        branches: [ "develop" ]
    workflow_dispatch:

jobs:
    build:
        name: get android version
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            -   name: set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle
            - name: Get Android version
              run: |
                  echo "VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_OUTPUT
              id: android_version
            - name: Get Version
              run: |
                  echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
            - name: check version
              run: |
                  echo "${{ env.version_name }}"
