name: Android CD

on:
    pull_request:
        branches: [ "develop" ]
    workflow_dispatch:

jobs:
    build:
        name: get android version
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: 17
            - name: Get Android version
              id: test
              uses: ltDino/android-get-version-action@v1.0
              with:
                  gradlePath: app/build.gradle.kts # or app/build.gradle.kts
            - name: Get the output
              run: |
                  echo "The versionCode was ${{ steps.test.outputs.versionCode }}"
                  echo "The versionName was ${{ steps.test.outputs.versionName }}"
