name: Slack Test

on:
    workflow_dispatch:

jobs:
    slack:
        name: Slack message
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
            - name: save Version
              run: |
                versionName=$(grep "versionName" ./app/build.gradle.kts | awk -F'=' '{ print $2 }' | tr -d ' "')
                echo "version_name=$versionName" >> $GITHUB_ENV
            - name: check version
              run: |
                echo "${{ env.version_name }}"
            - name: send message
              run: |
                  curl -H "Content-type: application/json" \
                  --data '{"channel":"$(${{ secrets.CREDENTIAL_FILE_CONTENT }})","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"터미널 슬랙 메세지 테스트"}}]}' \
                  -H "Authorization: Bearer $(${{ secrets.SLACK_AUTHORIZATION }})" \
                  -X POST https://slack.com/api/chat.postMessage
