name: Slack Test

on:
    workflow_dispatch:

jobs:
    slack:
        name: Slack message
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
            - name: save Version
              run: |
                versionName=$(grep "versionName" ./app/build.gradle.kts | awk -F'=' '{ print $2 }' | tr -d ' "')
                echo "version_name=$versionName" >> $GITHUB_ENV
            - name: check version
              run: |
                echo "${{ env.version_name }}"
            - name: send message
              run: |
                  curl -H "Content-type: application/json" \
                  --data '{"channel":"${{ secrets.SLACK_CHANNEL_ID }}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"[AOS][테스트중입니다.] 안드로이드 파이어베이스 v${{ env.version_name }}버전 배포 완료\n #배포 내용\n $(sed -n '/### 기능 수정/,$p' ${{ github.workspace}}/.github/body.md)\n"}]}' \
                  -H "Authorization: Bearer ${{ secrets.SLACK_AUTHORIZATION }}" \
                  -X POST https://slack.com/api/chat.postMessage
